name: UCSD CSE SPIS 2016 FOCS
github_url: https://github.com/ucsd-cse-spis-2016/ucsd-cse-spis-2016.github.io
mentor_url: mentor.html

url: https://ucsd-cse-spis-2016.github.io/

piazza: https://piazza.com/class/ioizytqm23v67l

weekly_google_calendar_prefix: "https://sites.google.com/a/eng.ucsd.edu/spis/home/AcademicProgram/2016-foundations#week"

google_calendar_embed: "https://calendar.google.com/calendar/embed?mode=AGENDA&amp;height=300&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=eng.ucsd.edu_vpkdu3a26k3alf8rt2m19054ug%40group.calendar.google.com&amp;color=%232F6213&amp;ctz=America%2FLos_Angeles"

google_calendar_embed_height_600px: "https://calendar.google.com/calendar/embed?mode=AGENDA&amp;height=300&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=eng.ucsd.edu_vpkdu3a26k3alf8rt2m19054ug%40group.calendar.google.com&amp;color=%232F6213&amp;ctz=America%2FLos_Angeles"

course_github_url: https://github.com/ucsd-cse-spis-2016


num_weeks: 5
start_date: 2016-07-31 00:00:00.00-7:00

hwk_course: "CSE SPIS"
course: "UCSD CSE SPIS: Foundations of Computer Science (FOCS)"
year: "2016"

kramdown:
   parse_block_html: true

exclude: [vendor]

timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  info:
    output: true
    permalink: /info/:path/
  topics:
    output: true
    permalink: /topics/:path/
  webapps:
    output: true
    permalink: /webapps/:path/
  bigdata:
    output: true
    permalink: /bigdata/:path/
  robotics:
    output: true
    permalink: /robotics/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
